Resolves #1245 Change Dialog titles to one related to their function
borgbase/vorta pull request #1246
Opened 2022-03-30 05:38 UTC by delfino-nunez

Titles changed and translated.

### English
Diff
![Diff: Choose archives for diff_001](https://user-images.githubusercontent.com/770967/160758664-fb43ebcd-d812-47b8-8731-96b65859bfca.png)

Diff Results
![Diff Result_001](https://user-images.githubusercontent.com/770967/160758680-8d6b7025-7e9b-4c35-9ee9-9b5799098565.png)

Extract
![Extract: Choose files to extract_001](https://user-images.githubusercontent.com/770967/160758690-b18b8572-e421-4a82-89f5-d7dc07424c92.png)

### Translated
Diff
![Comparación: Seleccione los archivos para comparar_001](https://user-images.githubusercontent.com/770967/160758738-041f9917-dffa-4125-bdd2-a5d29abcec56.png)

Diff Results
![Resultado de la comparación_001](https://user-images.githubusercontent.com/770967/160758742-789ad773-d8f8-440b-9803-0b92bb2a658f.png)

Extract
![Extraer: Seleccione los ficheros para extraer_001](https://user-images.githubusercontent.com/770967/160758730-e52f642e-820e-4521-9d82-0884c062a0c2.png)

2022-03-30 12:32 UTC, real-yfprojects requested changes

2022-03-30 12:32 UTC, real-yfprojects commented on src/vorta/assets/UI/extractdialog.ui
> +   <string>Extract: Choose files to extract</string>
```suggestion
   <string>Choose files to extract</string>
```
Bad style and doubling

2022-03-30 12:32 UTC, real-yfprojects commented on src/vorta/assets/UI/diffdialog.ui
> +   <string>Diff: Choose archives for diff</string>
```suggestion
   <string>Choose archives for diff</string>
```
Bad style and doubling

2022-03-31 04:31 UTC, delfino-nunez commented on src/vorta/assets/UI/extractdialog.ui
> +   <string>Extract: Choose files to extract</string>
Changed.

2022-03-31 04:40 UTC, real-yfprojects commented on src/vorta/assets/UI/extractdialog.ui
> +   <string>Extract: Choose files to extract</string>
No this one isn't.

2022-04-01 05:14 UTC, delfino-nunez commented on src/vorta/assets/UI/extractdialog.ui
> +   <string>Extract: Choose files to extract</string>
both should be changed now.

2022-04-01 14:36 UTC, real-yfprojects approved these changes

2022-04-02 05:28 UTC, merged

2022-04-02 05:28 UTC, m3nu commented
Thanks for changing and reviewing, guys!