Flatpak updates
borgbase/vorta pull request #1478
Opened 2022-11-07 15:21 UTC by Hofer-Julian

1. Removes flatpak folder
2. Updates `flatpak-install` rule

Further descriptions are in the commit messages.

If it's not too much work, a minor release would be appreciated after this PR has been merged

2022-11-07 21:27 UTC, m3nu commented
No problem. We're in the middle of releasing anyways.

2022-11-07 21:28 UTC, m3nu commented
`make bump-version` has a line to add the current version to Flatpak. This could need adjusting too?

2022-11-08 05:49 UTC, Hofer-Julian commented
> `make bump-version` has a line to add the current version to Flatpak. This could need adjusting too?

You mean bumping the version in the xml?
That's fine, we are still going to use that. As a sidenote, it's called flatpak xml here, but I am pretty sure all distros use it that package vorta.

2022-11-08 07:56 UTC, real-yfprojects commented
> The building happens at flathub, and we don't use this one for anything at the moment

... and the build instructions are stored in the flathub repository. So why keep the `flatpak-install` make command when it can only be used with assets that aren't stored in this repo? Also this make command is not referenced any longer: https://github.com/flathub/com.borgbase.Vorta/commit/10f3bb518000eee4de7641749fe16271d2fdfe8f

2022-11-08 07:59 UTC, Hofer-Julian commented
> So why keep the flatpak-install make command when it can only be used with assets that aren't stored in this repo?

I have a slight preference to keep it here, but I don't mind either way

> Also this make command is not referenced any longer: 

I would reference it again after this PR is merged and released

2022-11-08 08:06 UTC, real-yfprojects requested changes

2022-11-08 08:08 UTC, Hofer-Julian commented on Makefile
> -	install -D ${FLATPAK_XML} /app/share/metainfo/com.borgbase.Vorta.appdata.xml
Ah good catch, that was unintentional.
Will fix right away.

2022-11-08 08:12 UTC, Hofer-Julian commented on Makefile
> -	install -D ${FLATPAK_XML} /app/share/metainfo/com.borgbase.Vorta.appdata.xml
I've also renamed the misleading `FLATPAK_XML` to `APPSTREAM_METADATA`.

2022-11-08 11:26 UTC, real-yfprojects approved these changes
Looks fine to me.

2022-11-08 11:31 UTC, merged