Change colour of added and removed text
borgbase/vorta pull request #649
Opened 2020-09-13 03:06 UTC by samuel-w

This is what the colours for added files are. Really bright and hard to read.
![example](https://user-images.githubusercontent.com/67625312/93009240-05ac9880-f544-11ea-9df4-7317dc16af82.png)
This is what they look like now.
![example2](https://user-images.githubusercontent.com/67625312/93009246-14934b00-f544-11ea-8c10-160d0299c85e.png)

2020-09-13 03:18 UTC, m3nu commented
How about dark themes?

For links I changed from dark blue to a lighter blue because it works on light and dark equally.

2020-09-13 03:25 UTC, samuel-w commented
This is what it looks like in dark mode. Looks fine to me.
![example3](https://user-images.githubusercontent.com/67625312/93009437-c6337b80-f546-11ea-853f-527baf58ad27.png)

2020-09-13 04:00 UTC, m3nu commented
Dark red also OK?

2020-09-13 04:28 UTC, samuel-w commented
I changed it so that it only sets the colours to dark when running in light mode.

2020-09-13 04:41 UTC, m3nu approved these changes

2020-09-27 07:21 UTC, m3nu requested changes
See comment to reduce calling `uses_dark_mode()` repeatedly. May be a heavy function and it would be called *very* often for each line.

2020-09-27 21:57 UTC, samuel-w commented on src/vorta/views/diff_result.py
> +                return QVariant(QColor(Qt.red)) if uses_dark_mode() else QVariant(QColor(Qt.darkRed))
It's only called in two areas,  here and in icon colourization. I did change it so `uses_dark_mode` is only called once in `diff_result`

2020-12-04 02:29 UTC, samuel-w commented
Now the colours are object variables, and dark_mode is only called at init

2020-12-04 07:10 UTC, m3nu approved these changes

2020-12-04 07:13 UTC, merged