Add mount option override checkbox
borgbase/vorta pull request #682
Opened 2020-10-07 00:12 UTC by samuel-w

Replaces #522, fixes #520

2020-12-15 09:27 UTC, m3nu approved these changes

2020-12-16 03:25 UTC, m3nu requested changes

2020-12-16 03:47 UTC, samuel-w commented on src/vorta/assets/UI/archivetab.ui
> +          <string>Tick this box if there are permission errors on the mounted archive</string>
It's the best place to put it IMO. If it was put in the global settings it would make no sense. I'll try making it a right click option.

2020-12-16 08:42 UTC, samuel-w commented on src/vorta/assets/UI/archivetab.ui
> +          <string>Tick this box if there are permission errors on the mounted archive</string>
Actually, it can't be a right click option, since https://github.com/borgbase/vorta/pull/571 would conflict with this.

2021-02-18 06:27 UTC, m3nu commented
Minor nitpick: I prefer to have this option in the misc tab. Why?

- I doesn't clutter the archive tab.
- Not used often.
- If it's used, I may use it for multiple profiles (e.g. if I often restore data from NAS backups)
- No need to pass new options around.

2021-02-18 06:32 UTC, samuel-w commented
Seems reasonable.

2021-02-18 07:01 UTC, merged